news_encoder: 
  learning_rate: 3e-6
  projection_dim: 64
  
user_encoder: 
  learning_rate: 1e-4
  projection_dim: 64
  n_layers: 1
  
general: 
  seed: 42
  batch_size: 32
  num_workers: 4
  max_epochs: 5
  early_stopping: 3
  max_history_length: 35
  max_title_length: 20
  embedding_dim: 64
  candidate_k: 5

logging: 
  step: 2
  
checkpoint: 
  topk_model: 2
  save_dir: "./results"
